#+SETUPFILE:~/.emacs.d/org-templates/level-1.org
#+Title: 2P fagdag - Statistikkoppgaver
Du er elev {ELEVNUMMER} i klasse {KLASSE} og har valgt oppgavenivå {LEVEL}.

* Definisjon
Gjør rede for følgende begrep og gi et eksempel på hver:

{DEFINISJONSOPPGAVE}

* Bruk av sentral- og spredningsmål
Finn /median/, /gjennomsnitt/, /kvartilbredde/ og /standardavvik/ for følgende verdier:

{SENTRALMAALSOPPGAVE}
* Frekvenstabell
Finn {FREKVENSTABELLTEKST} for dataene i frekvenstabellen under.

{FREKVENSTABELLHEADING}
|-|-|
{FREKVENSTABELLDATA}

* Den nye læreren
{NYTTSNITT}
 
* Diagramtolkning
Diagrammet under viser visualiseringen av to datasett. Hva kan du si om sentral- og spredningsmål for de to i forhold til hverandre?

{DIAGRAM}

* Histogrammet
Histogrammet under viser fordelingen av svar på en "hvor mange pastiller er det i krukka"-oppgave, hvor  mange deltok?

{HISTOGRAM}

{HISTOGRAMADD}
* Kumulativ match
Under vises et stolpediagram og fire foreslåtte kummulative grafer. Hvilken av de fire alternativene tilhører dataene fra stolpediagrammet?

{KUMMULATIVMATCH}

* Foreslå visualisering
Velg to av pounktene under og illustrer dem i hvert sitt diagram. Begrunn valget av diagram.

- Karakterfordelingen i en klasse etter en prøve (rundt 30 elever)
- Karakterfordelingen for en /skole/ etter en heldagsprøve i norsk (rundt 600 elever)
- Gjennomsnittskarakteren for årets FIFA-spill for årene 1996 til 2017.
- Aldersfordelingen for de som ser på Dagsrevyen mer enn to ganger hver uke.

* Skisser
For to av punktene i forrige oppgave, skisser hvordan en slik fordeling /kan/ se ut.

* Statistisk analyse
{ANALYSEOPPGAVE}
