#+SETUPFILE:orgheader_nojs.org
#+Title: 2P fagdag - Statistikkoppgaver
Du er elev {ELEVNUMMER} i klasse {KLASSE}.

* Definisjon
Gjør rede for følgende begrep og gi et eksempel på hver:

{DEFINISJONSOPPGAVE}

* Bruk av sentral- og spredningsmål
Finn /median/, /gjennomsnitt/, /kvartilbredde/ og /standardavvik/ for følgende verdier:

{SENTRALMAALSOPPGAVE}
* Frekvenstabell
Velg en av frekvenstabellene under. Velger du den første, skal du finne /median/, /typetall/, /gjennomsnitt/ og /variasjonsbredde/. Velger du den andre, skal du kun finne /median/ og /gjennomsnitt/.

*Alternativ 1*
{FREKVENSTABELLHEADINGA}
|-|-|
{FREKVENSTABELLDATAA}

*Alternativ 2*
{FREKVENSTABELLHEADINGB}
|-|-|
{FREKVENSTABELLDATAB}

* Den nye læreren
{NYTTSNITT}
 
* Diagramtolkning
Diagrammet under viser visualiseringen av to datasett. Hva kan du si om sentral- og spredningsmål for de to i forhold til hverandre?

{DIAGRAM}

* Histogrammet
Histogrammet under viser fordelingen av svar på en "hvor mange pastiller er det i krukka"-oppgave, hvor  mange deltok?

{HISTOGRAM}

{HISTOGRAMADD}
* Kumulativ match
Under vises et stolpediagram og fire foreslåtte kummulative grafer. Hvilken av de fire alternativene tilhører dataene fra stolpediagrammet?

{KUMMULATIVMATCH}

* Foreslå visualisering
Velg to av pounktene under og illustrer dem i hvert sitt diagram. Begrunn valget av diagram.

- Karakterfordelingen i en klasse etter en prøve (rundt 30 elever)
- Karakterfordelingen for en /skole/ etter en heldagsprøve i norsk (rundt 600 elever)
- Gjennomsnittskarakteren for årets FIFA-spill for årene 1996 til 2017.
- Aldersfordelingen for de som ser på Dagsrevyen mer enn to ganger hver uke.

* Skisser
For to av punktene i forrige oppgave, skisser hvordan en slik fordeling /kan/ se ut.

* Statistisk analyse
Velg én av de to alternative oppgavene under.

*Alternativ 1*
{ANALYSEOPPGAVEA}

*Alternativ 2*
{ANALYSEOPPGAVEB}
